<a href="https://colab.research.google.com/github/caiobaptistaa/Econometria-4_PUC-Rio/blob/main/Trabalho_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Trabalho Econometria 4 - Feature Engineering <h1>

In [3]:
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
pd.pandas.set_option('display.max_columns', None)

from sklearn.preprocessing import StandardScaler


def check_stationarity(series):

    result = adfuller(series.values)

    print('ADF Statistic: %f' % result[0])
    print('p-value: %f' % result[1])
    print('Critical Values:')
    for key, value in result[4].items():
        print('\t%s: %.3f' % (key, value))

    if (result[1] <= 0.05) & (result[4]['5%'] > result[0]):
        print("\u001b[32mStationary\u001b[0m")
    else:
        print("\x1b[31mNon-stationary\x1b[0m")

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [4]:
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv('/content/drive/MyDrive/Trabalho-1/current.csv', sep= ",", low_memory= False)

Mounted at /content/drive

In [5]:
data.tail()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,IPDCONGD,IPNCONGD,IPBUSEQ,IPMAT,IPDMAT,IPNMAT,IPMANSICS,IPB51222S,IPFUELS,CUMFNS,HWI,HWIURATIO,CLF16OV,CE16OV,UNRATE,UEMPMEAN,UEMPLT5,UEMP5TO14,UEMP15OV,UEMP15T26,UEMP27OV,CLAIMSx,PAYEMS,USGOOD,CES1021000001,USCONS,MANEMP,DMANEMP,NDMANEMP,SRVPRD,USTPU,USWTRADE,USTRADE,USFIRE,USGOVT,CES0600000007,AWOTMAN,AWHMAN,HOUST,HOUSTNE,HOUSTMW,HOUSTS,HOUSTW,PERMIT,PERMITNE,PERMITMW,PERMITS,PERMITW,ACOGNO,AMDMNOx,ANDENOx,AMDMUOx,BUSINVx,ISRATIOx,M1SL,M2SL,M2REAL,BOGMBASE,TOTRESNS,NONBORRES,BUSLOANS,REALLN,NONREVSL,CONSPI,S&P 500,S&P: indust,S&P div yield,S&P PE ratio,FEDFUNDS,CP3Mx,TB3MS,TB6MS,GS1,GS5,GS10,AAA,BAA,COMPAPFFx,TB3SMFFM,TB6SMFFM,T1YFFM,T5YFFM,T10YFFM,AAAFFM,BAAFFM,TWEXAFEGSMTHx,EXSZUSx,EXJPUSx,EXUSUKx,EXCAUSx,WPSFD49207,WPSFD49502,WPSID61,WPSID62,OILPRICEx,PPICMM,CPIAUCSL,CPIAPPSL,CPITRNSL,CPIMEDSL,CUSR0000SAC,CUSR0000SAD,CUSR0000SAS,CPIULFSL,CUSR0000SA0L2,CUSR0000SA0L5,PCEPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,UMCSENTx,DTCOLNVHFNM,DTCTHFNM,INVEST,VIXCLSx
756,12/1/2021,17791.488,14465.3,123.868,1562935.0,634393.0,101.7015,100.8807,101.3610,100.3458,103.9402,99.3044,95.9503,102.5954,99.6077,98.9175,100.3902,98.0082,92.6118,77.1177,11448.0,1.811679,162294,155975,3.9,28.6,1977,1571,2788,780,2008,221750,149240,20691,545.3,7546,12555,7816,4739,128549,28163,5749.7,15595.1,8863,22141,41.0,4.1,41.4,1768,141,335,901,391,1896.0,272.0,260.0,941.0,423.0,210583.0,256464.0,80389.0,1078952.0,2212216.0,1.29,20423.6,21483.2,7669.1,6413100,4187.9,4149900,2478.0085,4787.7529,3390.22285,0.160521,4674.77,6561.93,1.291980,30.690714,0.08,0.17,0.06,0.15,0.30,1.23,1.47,2.65,3.30,0.09,-0.02,0.07,0.22,1.15,1.38,2.56,3.22,108.2017,0.9210,113.8329,1.3303,1.2800,232.047,249.019,248.616,265.799,71.71,269.049,280.126,124.117,250.105,531.268,210.452,126.416,348.100,278.963,258.978,268.054,118.709,95.669,106.351,126.834,27.17,31.25,24.38,70.6,370554.92,753781.25,5678.9640,21.2985
757,1/1/2022,17711.363,14444.5,125.781,1581814.0,651557.0,102.5596,101.7294,102.2818,101.6742,105.6880,100.5197,95.5580,103.4640,99.2770,98.6817,100.2896,107.8310,89.7379,77.0128,11283.0,1.732381,163687,157174,4.0,24.6,2417,1607,2507,816,1691,227600,149744,20723,545.5,7552,12581,7826,4755,129021,28351,5762.3,15716.5,8865,22153,40.7,4.2,41.2,1666,105,196,919,446,1841.0,151.0,270.0,958.0,462.0,213272.0,264356.0,87017.0,1088546.0,2239547.0,1.26,20582.3,21659.2,7682.4,6103900,3871.1,3839100,2477.0797,4804.5980,3396.98130,0.160759,4573.82,6372.98,1.331960,28.275030,0.08,0.22,0.15,0.33,0.55,1.54,1.76,2.93,3.58,0.14,0.07,0.25,0.47,1.46,1.68,2.85,3.50,107.6318,0.9191,114.8255,1.3555,1.2622,235.764,253.449,253.997,273.507,83.22,282.527,281.933,125.433,251.210,534.798,212.082,127.892,350.115,280.656,261.099,269.778,119.307,96.593,107.154,127.248,27.31,31.44,24.51,67.2,370286.86,751635.23,5777.3631,22.9143
758,2/1/2022,17727.726,14485.8,125.878,1570284.0,662321.0,103.5845,102.9275,103.3749,102.3062,103.8407,101.8127,97.3472,104.2679,101.9388,100.5519,101.6112,113.8502,93.9648,77.9996,11344.0,1.809250,163991,157722,3.8,26.6,2131,1800,2437,735,1702,195000,150458,20837,554.7,7606,12631,7846,4785,129621,28562,5788.8,15827.8,8894,22163,41.4,4.4,41.6,1777,134,234,999,410,1857.0,179.0,249.0,954.0,475.0,216803.0,262494.0,83414.0,1095638.0,2279547.0,1.27,20667.3,21750.3,7653.7,6040000,3804.5,3775800,2482.7913,4830.7663,3420.48079,0.160862,4435.98,6159.67,1.385166,NaN,0.08,0.38,0.33,0.64,1.00,1.81,1.93,3.25,3.97,0.30,0.25,0.56,0.92,1.73,1.85,3.17,3.89,107.8260,0.9228,115.2763,1.3540,1.2711,241.677,261.145,257.878,300.730,91.64,296.755,284.182,126.342,256.028,535.732,214.826,128.479,351.797,282.799,263.535,272.086,119.945,96.426,109.075,127.566,27.42,31.60,24.56,62.8,374193.90,753730.65,5818.5663,26.1429
759,3/1/2022,17666.265,14447.6,126.480,1551969.0,671648.0,104.4741,103.6544,104.3039,103.0778,107.3327,101.8590,98.7428,105.3626,102.3729,100.8191,102.4726,109.2150,94.8724,78.6364,11549.0,1.940356,164409,158458,3.6,24.2,2289,1684,1999,571,1428,178000,150886,20904,558.4,7626,12674,7871,4803,129982,28621,5813.5,15852.3,8906,22167,40.9,4.2,41.5,1728,237,236,837,418,1879.0,185.0,260.0,972.0,462.0,225160.0,264153.0,83034.0,1100764.0,2324248.0,1.27,20709.6,21809.2,7580.3,6134500,3874.7,3848500,2527.6346,4864.9312,3441.54588,0.160967,4391.27,6104.43,1.411210,NaN,0.20,0.73,0.44,0.83,1.34,2.11,2.13,3.43,4.29,0.53,0.24,0.63,1.14,1.91,1.93,3.23,4.09,109.6905,0.9294,118.5774,1.3168,1.2660,246.637,267.671,263.439,306.279,108.50,302.329,287.708,127.044,266.004,538.665,219.353,127.283,354.126,286.418,267.738,275.635,121.024,96.265,112.130,128.165,27.50,31.67,24.71,59.4,369346.54,747716.57,5822.2776,26.9368
760,4/1/2022,17696.358,14486.7,127.304,NaN,677711.0,105.5973,104.5589,105.2742,103.8804,108.8943,102.4591,99.8258,106.7616,103.5346,101.7100,103.2481,112.6138,93.2678,79.2107,NaN,NaN,164046,158105,3.6,25.0,2227,1617,2033,551,1483,184400,151314,20970,567.3,7628,12729,7902,4827,130344,28725,5835.7,15881.5,8941,22189,40.8,4.1,41.4,1724,182,184,926,432,1823.0,163.0,250.0,989.0,421.0,NaN,265326.0,83398.0,1106667.0,NaN,NaN,20620.5,21728.0,7527.1,5885200,3615.4,3591400,2559.4241,4920.3396,NaN,NaN,4391.30,6111.81,NaN,NaN,0.33,0.91,0.76,1.23,1.89,2.78,2.75,3.76,4.66,0.58,0.43,0.90,1.56,2.45,2.42,3.43,4.33,111.7008,0.9450,126.3743,1.2933,1.2628,248.649,269.513,269.140,322.404,101.78,302.651,288.663,126.087,264.995,541.057,218.699,127.351,356.803,287.132,268.397,276.522,121.323,96.346,111.805,128.757,27.56,31.73,24.78,65.2,NaN,NaN,5812.8872,24.4850

In [6]:
data.shape

(761, 128)

In [7]:
[col for col in data.columns if data[col].isnull().any()]

['CMRMTSPLx',
 'HWI',
 'HWIURATIO',
 'PERMIT',
 'PERMITNE',
 'PERMITMW',
 'PERMITS',
 'PERMITW',
 'ACOGNO',
 'ANDENOx',
 'BUSINVx',
 'ISRATIOx',
 'NONREVSL',
 'CONSPI',
 'S&P div yield',
 'S&P PE ratio',
 'CP3Mx',
 'COMPAPFFx',
 'TWEXAFEGSMTHx',
 'UMCSENTx',
 'DTCOLNVHFNM',
 'DTCTHFNM',
 'VIXCLSx']

Dropping all columns with NaN values.

In [8]:
data.dropna(axis= 1, inplace= True)

In [9]:
data.shape

(761, 105)

In [10]:
data.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,IPDCONGD,IPNCONGD,IPBUSEQ,IPMAT,IPDMAT,IPNMAT,IPMANSICS,IPB51222S,IPFUELS,CUMFNS,CLF16OV,CE16OV,UNRATE,UEMPMEAN,UEMPLT5,UEMP5TO14,UEMP15OV,UEMP15T26,UEMP27OV,CLAIMSx,PAYEMS,USGOOD,CES1021000001,USCONS,MANEMP,DMANEMP,NDMANEMP,SRVPRD,USTPU,USWTRADE,USTRADE,USFIRE,USGOVT,CES0600000007,AWOTMAN,AWHMAN,HOUST,HOUSTNE,HOUSTMW,HOUSTS,HOUSTW,AMDMNOx,AMDMUOx,M1SL,M2SL,M2REAL,BOGMBASE,TOTRESNS,NONBORRES,BUSLOANS,REALLN,S&P 500,S&P: indust,FEDFUNDS,TB3MS,TB6MS,GS1,GS5,GS10,AAA,BAA,TB3SMFFM,TB6SMFFM,T1YFFM,T5YFFM,T10YFFM,AAAFFM,BAAFFM,EXSZUSx,EXJPUSx,EXUSUKx,EXCAUSx,WPSFD49207,WPSFD49502,WPSID61,WPSID62,OILPRICEx,PPICMM,CPIAUCSL,CPIAPPSL,CPITRNSL,CPIMEDSL,CUSR0000SAC,CUSR0000SAD,CUSR0000SAS,CPIULFSL,CUSR0000SA0L2,CUSR0000SA0L5,PCEPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,INVEST
0,Transform:,5.000,5.0,5.000,5.00000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,2.0000,5,5,2.0,2.0,5,5,5,5,5,5,5,5,5.0,5,5,5,5,5,5,5.0,5.0,5,5,1.0,2.0,1.0,4,4,4,4,4,5.00000,5.00000,6.0,6.0,5.0,6,6.0,7,6.0000,6.0000,5.00,5.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,5.0000,5.0000,5.0000,5.0000,6.0,6.0,6.0,6.0,6.00,6.0,6.00,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.000,6.000,6.000,6.000,6.00,6.00,6.00,6.0000
1,1/1/1959,2442.158,2293.2,17.272,18235.77392,22.0733,23.4027,22.2858,31.5688,18.6601,38.1454,8.1760,20.2407,12.2794,30.6469,20.9189,19.9060,34.7139,80.1973,67936,63868,6.0,16.3,1574,1169,1396,594,802,291078,52478,18796,713.0,2993,14998,8740,6258,33682,10774,2568.7,5350.3,2418,8105,39.8,2.5,40.2,1657,350,452,505,350,14716.48296,42620.34624,138.9,286.6,987.9,50500,18.9,18300,35.2130,24.9242,55.62,59.30,2.48,2.82,3.09,3.36,4.01,4.02,4.12,4.87,0.34,0.61,0.88,1.53,1.54,1.64,2.39,4.3122,359.8417,2.8065,0.9671,33.1,33.4,30.6,31.6,3.00,32.5,29.01,44.8,29.3,21.1,33.3,38.1,22.9,28.9,30.7,29.6,16.042,56.918,17.791,11.326,2.13,2.45,2.04,84.2043
2,2/1/1959,2451.778,2301.5,17.452,18369.56308,22.5056,23.7185,22.4788,31.8004,18.7580,38.5100,8.2854,20.8817,12.8450,31.1834,21.3034,19.8518,34.2411,81.4428,67649,63684,5.9,15.5,1554,1164,1277,545,732,282958,52688,18890,704.2,2980,15115,8839,6276,33798,10816,2575.4,5381.3,2420,8116,39.7,2.6,40.3,1667,346,469,508,344,15400.24873,43677.15151,139.4,287.7,992.1,49800,18.6,18100,35.2201,25.2270,54.77,58.33,2.43,2.70,3.13,3.54,3.96,3.96,4.14,4.89,0.27,0.70,1.11,1.53,1.53,1.71,2.46,4.3133,359.8417,2.8093,0.9748,33.2,33.4,30.7,31.4,3.00,32.5,29.00,44.7,29.4,21.2,33.3,38.1,23.0,28.9,30.7,29.6,16.057,56.951,17.798,11.343,2.14,2.46,2.05,83.5280
3,3/1/1959,2467.594,2318.5,17.617,18523.05762,22.8298,23.8621,22.5892,31.8004,19.1254,38.3277,8.3749,21.4240,13.3511,31.6519,21.6367,19.9873,35.1079,82.4769,68068,64267,5.6,15.3,1459,1093,1210,530,680,260346,53014,19069,704.1,3013,15259,8965,6294,33945,10873,2584.4,5431.6,2430,8132,40.0,2.8,40.4,1620,330,413,503,374,15745.42348,44781.64655,139.7,289.2,998.3,49700,18.4,17800,35.1304,25.4218,56.16,59.79,2.80,2.80,3.13,3.61,3.99,3.99,4.13,4.85,0.00,0.33,0.81,1.19,1.19,1.33,2.05,4.3228,359.8417,2.8127,0.9698,33.2,33.3,30.7,31.5,2.97,32.9,28.97,44.7,29.6,21.3,33.2,38.3,23.0,28.9,30.7,29.6,16.068,57.022,17.785,11.363,2.15,2.45,2.07,81.6405
4,4/1/1959,2483.671,2334.9,17.553,18534.46600,23.3161,24.2067,22.9201,32.3021,19.2478,38.9658,8.5937,22.0157,13.7530,32.6322,22.0981,20.0685,34.9503,83.9922,68339,64768,5.2,14.9,1494,934,1039,408,631,246413,53321,19269,705.2,3085,15385,9077,6308,34052,10905,2596.9,5395.4,2439,8142,40.2,2.9,40.5,1590,275,391,536,388,15919.42165,45522.74556,139.7,290.1,1001.0,50100,18.7,18000,35.5581,25.7261,57.10,60.92,2.96,2.95,3.27,3.72,4.12,4.12,4.23,4.86,-0.01,0.31,0.76,1.16,1.16,1.27,1.90,4.3226,359.8417,2.8165,0.9636,33.2,33.4,30.7,31.7,2.97,32.7,28.98,44.8,29.7,21.3,33.2,38.3,23.1,29.0,30.7,29.6,16.100,57.080,17.796,11.403,2.16,2.47,2.08,81.8099

Creating CPI series and add date time

In [11]:
CPI = data[["sasdate", "CPIAUCSL"]].copy()

In [12]:
data = data.drop(columns = "CPIAUCSL")

In [13]:
CPI.head()

      sasdate  CPIAUCSL
0  Transform:      6.00
1    1/1/1959     29.01
2    2/1/1959     29.00
3    3/1/1959     28.97
4    4/1/1959     28.98

In [14]:
CPI = CPI.drop([0])

In [15]:
CPI.head()

    sasdate  CPIAUCSL
1  1/1/1959     29.01
2  2/1/1959     29.00
3  3/1/1959     28.97
4  4/1/1959     28.98
5  5/1/1959     29.04

In [16]:
CPI["sasdate"] = CPI["sasdate"].str.replace("/1/", "-")
CPI.head()

  sasdate  CPIAUCSL
1  1-1959     29.01
2  2-1959     29.00
3  3-1959     28.97
4  4-1959     28.98
5  5-1959     29.04

In [17]:
CPI["sasdate"] = pd.to_datetime(CPI["sasdate"], format = "%m-%Y")

In [18]:
CPI.head()

     sasdate  CPIAUCSL
1 1959-01-01     29.01
2 1959-02-01     29.00
3 1959-03-01     28.97
4 1959-04-01     28.98
5 1959-05-01     29.04

Transformation of CPI: ΔCPIt/CPIt

In [19]:
CPI["CPIAUCSL"] = (CPI["CPIAUCSL"] - CPI["CPIAUCSL"].shift(1))/CPI["CPIAUCSL"]
CPI.head()

     sasdate  CPIAUCSL
1 1959-01-01       NaN
2 1959-02-01 -0.000345
3 1959-03-01 -0.001036
4 1959-04-01  0.000345
5 1959-05-01  0.002066

In [20]:
CPI = CPI.drop([1])
CPI.head()

     sasdate  CPIAUCSL
2 1959-02-01 -0.000345
3 1959-03-01 -0.001036
4 1959-04-01  0.000345
5 1959-05-01  0.002066
6 1959-06-01  0.002405

Manipulation and transformations of features

In [21]:
def tcode(data):
  for i in data.columns:
    if data.loc[0, i] == 2.0:
      data[i] = data[i] - data[i].shift(1)
    if data.loc[0, i] == 3.0:
      data[i] = (data[i] - data[i].shift(1))**2
    if data.loc[0, i] == 4.0:
      data[i] = np.log(data[i])
    if data.loc[0, i] == 5.0:
      data[i] = np.log(data[i]) - np.log(data[i].shift(1))
    if data.loc[0, i] == 6.0:
      data[i] = (np.log(data[i]) - np.log(data[i].shift(1)))**2
    if data.loc[0, i] == 7.0:
      data[i] = (data[i]/(data[i].shift(1) - 1)) - (data[i].shift(1)/(data[i].shift(2) - 1))
  return data

In [22]:
data.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,IPDCONGD,IPNCONGD,IPBUSEQ,IPMAT,IPDMAT,IPNMAT,IPMANSICS,IPB51222S,IPFUELS,CUMFNS,CLF16OV,CE16OV,UNRATE,UEMPMEAN,UEMPLT5,UEMP5TO14,UEMP15OV,UEMP15T26,UEMP27OV,CLAIMSx,PAYEMS,USGOOD,CES1021000001,USCONS,MANEMP,DMANEMP,NDMANEMP,SRVPRD,USTPU,USWTRADE,USTRADE,USFIRE,USGOVT,CES0600000007,AWOTMAN,AWHMAN,HOUST,HOUSTNE,HOUSTMW,HOUSTS,HOUSTW,AMDMNOx,AMDMUOx,M1SL,M2SL,M2REAL,BOGMBASE,TOTRESNS,NONBORRES,BUSLOANS,REALLN,S&P 500,S&P: indust,FEDFUNDS,TB3MS,TB6MS,GS1,GS5,GS10,AAA,BAA,TB3SMFFM,TB6SMFFM,T1YFFM,T5YFFM,T10YFFM,AAAFFM,BAAFFM,EXSZUSx,EXJPUSx,EXUSUKx,EXCAUSx,WPSFD49207,WPSFD49502,WPSID61,WPSID62,OILPRICEx,PPICMM,CPIAPPSL,CPITRNSL,CPIMEDSL,CUSR0000SAC,CUSR0000SAD,CUSR0000SAS,CPIULFSL,CUSR0000SA0L2,CUSR0000SA0L5,PCEPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,INVEST
0,Transform:,5.000,5.0,5.000,5.00000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,5.0000,2.0000,5,5,2.0,2.0,5,5,5,5,5,5,5,5,5.0,5,5,5,5,5,5,5.0,5.0,5,5,1.0,2.0,1.0,4,4,4,4,4,5.00000,5.00000,6.0,6.0,5.0,6,6.0,7,6.0000,6.0000,5.00,5.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,5.0000,5.0000,5.0000,5.0000,6.0,6.0,6.0,6.0,6.00,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.000,6.000,6.000,6.000,6.00,6.00,6.00,6.0000
1,1/1/1959,2442.158,2293.2,17.272,18235.77392,22.0733,23.4027,22.2858,31.5688,18.6601,38.1454,8.1760,20.2407,12.2794,30.6469,20.9189,19.9060,34.7139,80.1973,67936,63868,6.0,16.3,1574,1169,1396,594,802,291078,52478,18796,713.0,2993,14998,8740,6258,33682,10774,2568.7,5350.3,2418,8105,39.8,2.5,40.2,1657,350,452,505,350,14716.48296,42620.34624,138.9,286.6,987.9,50500,18.9,18300,35.2130,24.9242,55.62,59.30,2.48,2.82,3.09,3.36,4.01,4.02,4.12,4.87,0.34,0.61,0.88,1.53,1.54,1.64,2.39,4.3122,359.8417,2.8065,0.9671,33.1,33.4,30.6,31.6,3.00,32.5,44.8,29.3,21.1,33.3,38.1,22.9,28.9,30.7,29.6,16.042,56.918,17.791,11.326,2.13,2.45,2.04,84.2043
2,2/1/1959,2451.778,2301.5,17.452,18369.56308,22.5056,23.7185,22.4788,31.8004,18.7580,38.5100,8.2854,20.8817,12.8450,31.1834,21.3034,19.8518,34.2411,81.4428,67649,63684,5.9,15.5,1554,1164,1277,545,732,282958,52688,18890,704.2,2980,15115,8839,6276,33798,10816,2575.4,5381.3,2420,8116,39.7,2.6,40.3,1667,346,469,508,344,15400.24873,43677.15151,139.4,287.7,992.1,49800,18.6,18100,35.2201,25.2270,54.77,58.33,2.43,2.70,3.13,3.54,3.96,3.96,4.14,4.89,0.27,0.70,1.11,1.53,1.53,1.71,2.46,4.3133,359.8417,2.8093,0.9748,33.2,33.4,30.7,31.4,3.00,32.5,44.7,29.4,21.2,33.3,38.1,23.0,28.9,30.7,29.6,16.057,56.951,17.798,11.343,2.14,2.46,2.05,83.5280
3,3/1/1959,2467.594,2318.5,17.617,18523.05762,22.8298,23.8621,22.5892,31.8004,19.1254,38.3277,8.3749,21.4240,13.3511,31.6519,21.6367,19.9873,35.1079,82.4769,68068,64267,5.6,15.3,1459,1093,1210,530,680,260346,53014,19069,704.1,3013,15259,8965,6294,33945,10873,2584.4,5431.6,2430,8132,40.0,2.8,40.4,1620,330,413,503,374,15745.42348,44781.64655,139.7,289.2,998.3,49700,18.4,17800,35.1304,25.4218,56.16,59.79,2.80,2.80,3.13,3.61,3.99,3.99,4.13,4.85,0.00,0.33,0.81,1.19,1.19,1.33,2.05,4.3228,359.8417,2.8127,0.9698,33.2,33.3,30.7,31.5,2.97,32.9,44.7,29.6,21.3,33.2,38.3,23.0,28.9,30.7,29.6,16.068,57.022,17.785,11.363,2.15,2.45,2.07,81.6405
4,4/1/1959,2483.671,2334.9,17.553,18534.46600,23.3161,24.2067,22.9201,32.3021,19.2478,38.9658,8.5937,22.0157,13.7530,32.6322,22.0981,20.0685,34.9503,83.9922,68339,64768,5.2,14.9,1494,934,1039,408,631,246413,53321,19269,705.2,3085,15385,9077,6308,34052,10905,2596.9,5395.4,2439,8142,40.2,2.9,40.5,1590,275,391,536,388,15919.42165,45522.74556,139.7,290.1,1001.0,50100,18.7,18000,35.5581,25.7261,57.10,60.92,2.96,2.95,3.27,3.72,4.12,4.12,4.23,4.86,-0.01,0.31,0.76,1.16,1.16,1.27,1.90,4.3226,359.8417,2.8165,0.9636,33.2,33.4,30.7,31.7,2.97,32.7,44.8,29.7,21.3,33.2,38.3,23.1,29.0,30.7,29.6,16.100,57.080,17.796,11.403,2.16,2.47,2.08,81.8099

In [23]:
data = tcode(data)

In [24]:
data.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,IPDCONGD,IPNCONGD,IPBUSEQ,IPMAT,IPDMAT,IPNMAT,IPMANSICS,IPB51222S,IPFUELS,CUMFNS,CLF16OV,CE16OV,UNRATE,UEMPMEAN,UEMPLT5,UEMP5TO14,UEMP15OV,UEMP15T26,UEMP27OV,CLAIMSx,PAYEMS,USGOOD,CES1021000001,USCONS,MANEMP,DMANEMP,NDMANEMP,SRVPRD,USTPU,USWTRADE,USTRADE,USFIRE,USGOVT,CES0600000007,AWOTMAN,AWHMAN,HOUST,HOUSTNE,HOUSTMW,HOUSTS,HOUSTW,AMDMNOx,AMDMUOx,M1SL,M2SL,M2REAL,BOGMBASE,TOTRESNS,NONBORRES,BUSLOANS,REALLN,S&P 500,S&P: indust,FEDFUNDS,TB3MS,TB6MS,GS1,GS5,GS10,AAA,BAA,TB3SMFFM,TB6SMFFM,T1YFFM,T5YFFM,T10YFFM,AAAFFM,BAAFFM,EXSZUSx,EXJPUSx,EXUSUKx,EXCAUSx,WPSFD49207,WPSFD49502,WPSID61,WPSID62,OILPRICEx,PPICMM,CPIAPPSL,CPITRNSL,CPIMEDSL,CUSR0000SAC,CUSR0000SAD,CUSR0000SAS,CPIULFSL,CUSR0000SA0L2,CUSR0000SA0L5,PCEPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,INVEST
0,Transform:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.386294,1.386294,1.386294,1.386294,1.386294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1/1/1959,6.191199,6.128266,1.239649,8.201703,1.484931,1.543413,1.494512,1.842731,1.316950,2.031967,0.491765,1.398258,0.898485,1.813094,1.431215,1.381583,1.937702,78.1973,9.516883,9.455136,4.0,14.3,5.751938,5.454466,5.631928,4.777441,5.077671,10.971909,9.258711,8.231961,4.960044,6.394594,8.006234,7.466228,7.132178,8.815281,7.675453,6.241717,6.975470,6.181258,7.390799,39.8,0.5,40.2,7.412764,5.857933,6.113682,6.224558,5.857933,7.987286,9.050649,9.872131,14.948493,5.286144,81.684886,1.316532,NaN,3.131682e+00,2.028003,2.409105,2.473171,0.48,0.82,1.09,1.36,2.01,2.02,2.12,2.87,0.34,0.61,0.88,1.53,1.54,1.64,2.39,-0.147990,4.276226,-0.577500,-1.642891,2.916491,2.947390,2.654425,2.760242,0.480453,2.854345,4.041904,2.514851,1.581340,2.937103,3.416785,1.793932,2.471442,2.665067,2.547264,9.671755e-01,5.061835e+00,1.181424e+00,0.403659,1.072545,0.802227,1.163830,6.977451
2,2/1/1959,0.003931,0.003613,0.010368,0.007310,0.019395,0.013404,0.008623,0.007310,0.005233,0.009513,0.013292,0.031178,0.045032,0.017354,0.018214,-0.002727,-0.013714,1.2455,-0.004234,-0.002885,-0.1,-0.8,-0.012788,-0.004286,-0.089097,-0.086094,-0.091328,-0.028293,0.003994,0.004989,-0.012419,-0.004353,0.007771,0.011264,0.002872,0.003438,0.003891,0.002605,0.005777,0.000827,0.001356,39.7,0.1,40.3,7.418781,5.846439,6.150603,6.230481,5.840642,0.045416,0.024493,0.000013,0.000015,0.004242,0.000195,0.000256,-3049.010875,4.064649e-08,0.000146,-0.015400,-0.016493,-0.05,-0.12,0.04,0.18,-0.05,-0.06,0.02,0.02,0.27,0.70,1.11,1.53,1.53,1.71,2.46,0.000255,0.000000,0.000997,0.007930,0.000009,0.000000,0.000011,0.000040,0.000000,0.000000,0.000005,0.000012,0.000022,0.000000,0.000000,0.000019,0.000000,0.000000,0.000000,8.734933e-07,3.359517e-07,1.547478e-07,0.000002,0.000022,0.000017,0.000024,0.000065
3,3/1/1959,0.006430,0.007359,0.009410,0.008321,0.014303,0.006036,0.004899,0.000000,0.019397,-0.004745,0.010744,0.025639,0.038644,0.014912,0.015524,0.006802,0.024999,1.0341,0.006175,0.009113,-0.3,-0.2,-0.063081,-0.062936,-0.053893,-0.027909,-0.073688,-0.083287,0.006168,0.009431,-0.000142,0.011013,0.009482,0.014154,0.002864,0.004340,0.005256,0.003489,0.009304,0.004124,0.001969,40.0,0.2,40.4,7.390181,5.799093,6.023448,6.220590,5.924256,0.022166,0.024973,0.000005,0.000027,0.006230,0.000004,0.000117,-0.005645,6.502958e-06,0.000059,0.025062,0.024722,0.37,0.10,0.00,0.07,0.03,0.03,-0.01,-0.04,0.00,0.33,0.81,1.19,1.19,1.33,2.05,0.002200,0.000000,0.001210,-0.005142,0.000000,0.000009,0.000000,0.000010,0.000101,0.000150,0.000000,0.000046,0.000022,0.000009,0.000027,0.000000,0.000000,0.000000,0.000000,4.689852e-07,1.552290e-06,5.339021e-07,0.000003,0.000022,0.000017,0.000094,0.000522
4,4/1/1959,0.006494,0.007049,-0.003639,0.000616,0.021077,0.014338,0.014542,0.015653,0.006379,0.016511,0.025790,0.027244,0.029658,0.030501,0.021101,0.004054,-0.004499,1.5153,0.003973,0.007765,-0.4,-0.4,0.023706,-0.157205,-0.152362,-0.261610,-0.074787,-0.055003,0.005774,0.010434,0.001561,0.023615,0.008224,0.012416,0.002222,0.003147,0.002939,0.004825,-0.006687,0.003697,0.001229,40.2,0.1,40.5,7.371489,5.616771,5.968708,6.284134,5.961005,0.010990,0.016414,0.000000,0.000010,0.002701,0.000064,0.000262,0.027813,1.464372e-04,0.000142,0.016599,0.018723,0.16,0.15,0.14,0.11,0.13,0.13,0.10,0.01,-0.01,0.31,0.76,1.16,1.16,1.27,1.90,-0.000046,0.000000,0.001350,-0.006414,0.000000,0.000009,0.000000,0.000040,0.000000,0.000037,0.000005,0.000011,0.000000,0.000000,0.000000,0.000019,0.000012,0.000000,0.000000,3.958331e-06,1.033545e-06,3.823042e-07,0.000012,0.000022,0.000066,0.000023,0.000004

In [25]:
data = data.drop([0, 1])

In [26]:
data["sasdate"] = data["sasdate"].str.replace("/1/", "-")
data["sasdate"] = pd.to_datetime(data["sasdate"], format = "%m-%Y")
data.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,IPDCONGD,IPNCONGD,IPBUSEQ,IPMAT,IPDMAT,IPNMAT,IPMANSICS,IPB51222S,IPFUELS,CUMFNS,CLF16OV,CE16OV,UNRATE,UEMPMEAN,UEMPLT5,UEMP5TO14,UEMP15OV,UEMP15T26,UEMP27OV,CLAIMSx,PAYEMS,USGOOD,CES1021000001,USCONS,MANEMP,DMANEMP,NDMANEMP,SRVPRD,USTPU,USWTRADE,USTRADE,USFIRE,USGOVT,CES0600000007,AWOTMAN,AWHMAN,HOUST,HOUSTNE,HOUSTMW,HOUSTS,HOUSTW,AMDMNOx,AMDMUOx,M1SL,M2SL,M2REAL,BOGMBASE,TOTRESNS,NONBORRES,BUSLOANS,REALLN,S&P 500,S&P: indust,FEDFUNDS,TB3MS,TB6MS,GS1,GS5,GS10,AAA,BAA,TB3SMFFM,TB6SMFFM,T1YFFM,T5YFFM,T10YFFM,AAAFFM,BAAFFM,EXSZUSx,EXJPUSx,EXUSUKx,EXCAUSx,WPSFD49207,WPSFD49502,WPSID61,WPSID62,OILPRICEx,PPICMM,CPIAPPSL,CPITRNSL,CPIMEDSL,CUSR0000SAC,CUSR0000SAD,CUSR0000SAS,CPIULFSL,CUSR0000SA0L2,CUSR0000SA0L5,PCEPI,DDURRG3M086SBEA,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,INVEST
2,1959-02-01,0.003931,0.003613,0.010368,0.007310,0.019395,0.013404,0.008623,0.007310,0.005233,0.009513,0.013292,0.031178,0.045032,0.017354,0.018214,-0.002727,-0.013714,1.2455,-0.004234,-0.002885,-0.1,-0.8,-0.012788,-0.004286,-0.089097,-0.086094,-0.091328,-0.028293,0.003994,0.004989,-0.012419,-0.004353,0.007771,0.011264,0.002872,0.003438,0.003891,0.002605,0.005777,0.000827,0.001356,39.7,0.1,40.3,7.418781,5.846439,6.150603,6.230481,5.840642,0.045416,0.024493,0.000013,0.000015,0.004242,0.000195,0.000256,-3049.010875,4.064649e-08,0.000146,-0.015400,-0.016493,-0.05,-0.12,0.04,0.18,-0.05,-0.06,0.02,0.02,0.27,0.70,1.11,1.53,1.53,1.71,2.46,0.000255,0.0,0.000997,0.007930,0.000009,0.000000,0.000011,0.000040,0.000000,0.000000,0.000005,0.000012,0.000022,0.000000,0.000000,0.000019,0.000000,0.000000,0.000000,8.734933e-07,3.359517e-07,1.547478e-07,0.000002,0.000022,0.000017,0.000024,0.000065
3,1959-03-01,0.006430,0.007359,0.009410,0.008321,0.014303,0.006036,0.004899,0.000000,0.019397,-0.004745,0.010744,0.025639,0.038644,0.014912,0.015524,0.006802,0.024999,1.0341,0.006175,0.009113,-0.3,-0.2,-0.063081,-0.062936,-0.053893,-0.027909,-0.073688,-0.083287,0.006168,0.009431,-0.000142,0.011013,0.009482,0.014154,0.002864,0.004340,0.005256,0.003489,0.009304,0.004124,0.001969,40.0,0.2,40.4,7.390181,5.799093,6.023448,6.220590,5.924256,0.022166,0.024973,0.000005,0.000027,0.006230,0.000004,0.000117,-0.005645,6.502958e-06,0.000059,0.025062,0.024722,0.37,0.10,0.00,0.07,0.03,0.03,-0.01,-0.04,0.00,0.33,0.81,1.19,1.19,1.33,2.05,0.002200,0.0,0.001210,-0.005142,0.000000,0.000009,0.000000,0.000010,0.000101,0.000150,0.000000,0.000046,0.000022,0.000009,0.000027,0.000000,0.000000,0.000000,0.000000,4.689852e-07,1.552290e-06,5.339021e-07,0.000003,0.000022,0.000017,0.000094,0.000522
4,1959-04-01,0.006494,0.007049,-0.003639,0.000616,0.021077,0.014338,0.014542,0.015653,0.006379,0.016511,0.025790,0.027244,0.029658,0.030501,0.021101,0.004054,-0.004499,1.5153,0.003973,0.007765,-0.4,-0.4,0.023706,-0.157205,-0.152362,-0.261610,-0.074787,-0.055003,0.005774,0.010434,0.001561,0.023615,0.008224,0.012416,0.002222,0.003147,0.002939,0.004825,-0.006687,0.003697,0.001229,40.2,0.1,40.5,7.371489,5.616771,5.968708,6.284134,5.961005,0.010990,0.016414,0.000000,0.000010,0.002701,0.000064,0.000262,0.027813,1.464372e-04,0.000142,0.016599,0.018723,0.16,0.15,0.14,0.11,0.13,0.13,0.10,0.01,-0.01,0.31,0.76,1.16,1.16,1.27,1.90,-0.000046,0.0,0.001350,-0.006414,0.000000,0.000009,0.000000,0.000040,0.000000,0.000037,0.000005,0.000011,0.000000,0.000000,0.000000,0.000019,0.000012,0.000000,0.000000,3.958331e-06,1.033545e-06,3.823042e-07,0.000012,0.000022,0.000066,0.000023,0.000004
5,1959-05-01,0.005763,0.006616,0.012005,0.007803,0.014950,0.008269,0.009583,0.004768,0.020151,0.000000,0.031893,0.025433,0.034046,0.008942,0.013828,0.014735,-0.019350,0.9237,-0.002359,-0.001066,-0.1,-0.2,-0.010091,0.073266,-0.073886,-0.045120,-0.092936,0.002185,0.004286,0.005641,0.006784,0.000648,0.006608,0.009102,0.003008,0.003518,0.004027,0.004035,0.011224,0.003275,0.001350,40.3,0.0,40.7,7.311886,5.560682,5.872118,6.188264,5.981414,-0.043038,-0.003043,0.000051,0.000052,0.005181,0.000000,0.000029,-0.022349,4.337246e-04,0.000128,0.014949,0.019023,-0.06,-0.11,0.06,0.24,0.23,0.19,0.14,0.10,-0.06,0.43,1.06,1.45,1.41,1.47,2.06,0.000046,0.0,-0.000710,-0.000623,0.000009,0.000009,0.000042,0.000040,0.000000,0.000037,0.000005,0.000000,0.000022,0.000009,0.000007,0.000019,0.000012,0.000000,0.000000,3.123134e-07,2.765394e-06,1.141107e-06,0.000002,0.000021,0.000016,0.000000,0.000176
6,1959-06-01,0.003102,0.002974,0.003708,0.009064,0.001144,0.007034,0.007126,-0.004768,0.007452,-0.007044,0.023273,-0.006575,-0.007350,-0.003002,0.001142,0.005308,0.000000,-0.1473,0.001466,0.002316,-0.1,0.2,0.028659,-0.042689,-0.002075,0.062132,-0.048095,0.044765,0.002443,0.004325,0.007018,0.004202,0.004317,0.005335,0.002841,0.001374,0.001734,0.002834,0.002105,0.002857,-0.001227,40.2,0.0,40.6,7.315218,5.537334,5.837730,6.249975,5.961005,0.045693,0.007621,0.000013,0.000042,0.004066,0.000016,0.000029,-0.005743,5.158028e-04,0.000090,-0.008664,-0.005491,0.49,0.37,0.19,0.11,0.15,0.03,0.09,0.08,-0.18,0.13,0.68,1.11,0.95,1.07,1.65,-0.002617,0.0,-0.000711,-0.004162,0.000009,0.000009,0.000000,0.000041,0.000000,0.000009,0.000005,0.000011,0.000022,0.000000,0.000000,0.000000,0.000012,0.000011,0.000011,8.130923e-06,3.967639e-06,5.051574e-06,0.000013,0.000000,0.000065,0.000023,0.000651

In [27]:
data.to_csv("/content/drive/MyDrive/Trabalho-1/data.csv", index = False)

checking stationarity of the series

In [28]:
CPI.head()

     sasdate  CPIAUCSL
2 1959-02-01 -0.000345
3 1959-03-01 -0.001036
4 1959-04-01  0.000345
5 1959-05-01  0.002066
6 1959-06-01  0.002405

In [29]:
check_stationarity(CPI["CPIAUCSL"])

ADF Statistic: -2.766744
p-value: 0.063183
Critical Values:
	1%: -3.439
	5%: -2.865
	10%: -2.569
Non-stationary

In [30]:
CPI["CPIAUCSL_diff"] = CPI['CPIAUCSL'].diff()
CPI = CPI.dropna()
CPI.head()

     sasdate  CPIAUCSL  CPIAUCSL_diff
3 1959-03-01 -0.001036      -0.000691
4 1959-04-01  0.000345       0.001381
5 1959-05-01  0.002066       0.001721
6 1959-06-01  0.002405       0.000339
7 1959-07-01  0.001372      -0.001032

In [31]:
check_stationarity(CPI["CPIAUCSL_diff"])

ADF Statistic: -11.333683
p-value: 0.000000
Critical Values:
	1%: -3.439
	5%: -2.865
	10%: -2.569
Stationary

In [32]:
CPI.head()

     sasdate  CPIAUCSL  CPIAUCSL_diff
3 1959-03-01 -0.001036      -0.000691
4 1959-04-01  0.000345       0.001381
5 1959-05-01  0.002066       0.001721
6 1959-06-01  0.002405       0.000339
7 1959-07-01  0.001372      -0.001032

In [33]:
CPI.to_csv("/content/drive/MyDrive/Trabalho-1/CPI.csv", index = False)

In [34]:
date = CPI["sasdate"].copy()
date.head()

3   1959-03-01
4   1959-04-01
5   1959-05-01
6   1959-06-01
7   1959-07-01
Name: sasdate, dtype: datetime64[ns]

In [35]:
date.to_csv("/content/drive/MyDrive/Trabalho-1/date.csv", index = False)